AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "blog_pro305"

Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET,POST,DELETE,PUT,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  User:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: BlogUser
      Architectures:
        - x86_64
      Events:
        GetUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user
            Method: get
        GetPersonById:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/{id}
            Method: get
        CreatePerson:
          Type: Api
          Properties:
            Path: /user
            Method: post
        UpdatePerson:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: put
        DeletePerson:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: delete
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambdas/user
      DockerTag: python3.12-v1

  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
          Name: Id
          Type: String
      TableName: BlogUser